# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#' @useDynLib foofactors
#' @import Rcpp
#' @param x A single integer.
#' @export
#' @examples
#' timesTwo(10)
timesTwo <- function(x) {
    .Call('_foofactors_timesTwo', PACKAGE = 'foofactors', x)
}

